packages:
  - src/**/*
allowBuilds:
  '@biomejs/biome': true
  '@dfinity/pic': true
  '@reown/appkit': true
  esbuild: true
  sharp: true
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@reown/appkit'
  - esbuild
  - sharp
ignoredBuiltDependencies:
  - '@dfinity/pic'
