/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AllowlistedToken = IDL.Record({
  'decimals' : IDL.Nat,
  'tokenAddress' : IDL.Text,
  'chain' : IDL.Text,
  'name' : IDL.Text,
  'priceUSD' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const MinerId = IDL.Nat;
export const TribeId = IDL.Text;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Tribe = IDL.Record({
  'id' : TribeId,
  'coverImageUrl' : IDL.Opt(IDL.Text),
  'ownerId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'memberCount' : IDL.Nat,
  'description' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'cumulativeAkk' : IDL.Nat,
  'cumulativeGrit' : IDL.Nat,
});
export const TribeError = IDL.Variant({
  'nameTaken' : IDL.Null,
  'noUsername' : IDL.Null,
  'newOwnerMaxTribes' : IDL.Null,
  'descriptionTooLong' : IDL.Null,
  'notMember' : IDL.Null,
  'newOwnerNotFound' : IDL.Null,
  'alreadyMember' : IDL.Null,
  'notFound' : IDL.Null,
  'nameTooLong' : IDL.Null,
  'notOwner' : IDL.Null,
  'maxTribesReached' : IDL.Null,
  'newOwnerNoUsername' : IDL.Null,
});
export const MintRetryView = IDL.Record({
  'owner' : IDL.Principal,
  'lastAttemptTime' : IDL.Int,
  'blockId' : IDL.Nat,
  'minerId' : IDL.Text,
  'attempts' : IDL.Nat,
  'error' : IDL.Text,
  'amount' : IDL.Nat,
});
export const ClaimStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'pendingFee' : IDL.Null,
  'failed' : IDL.Null,
});
export const ClaimRecord = IDL.Record({
  'status' : ClaimStatus,
  'amountBurned' : IDL.Float64,
  'gritMinted' : IDL.Nat,
  'claimant' : IDL.Principal,
  'tokenAddress' : IDL.Text,
  'chain' : IDL.Text,
  'tokenDecimals' : IDL.Nat,
  'tokenSymbol' : IDL.Text,
  'usdValue' : IDL.Float64,
  'timestamp' : IDL.Int,
  'txHash' : IDL.Text,
  'feeTxHash' : IDL.Opt(IDL.Text),
});
export const AuditAction = IDL.Variant({
  'add' : IDL.Null,
  'remove' : IDL.Null,
});
export const AuditLogEntry = IDL.Record({
  'action' : AuditAction,
  'adminPrincipal' : IDL.Principal,
  'tokenAddress' : IDL.Text,
  'chain' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const BlockDetailView = IDL.Record({
  'winnerMinerId' : IDL.Opt(MinerId),
  'minerParticipants' : IDL.Vec(IDL.Tuple(MinerId, IDL.Principal)),
  'blockNumber' : IDL.Nat,
  'minerWeights' : IDL.Vec(IDL.Tuple(MinerId, IDL.Float64)),
  'vrfValue' : IDL.Nat64,
  'akkReward' : IDL.Nat,
  'winnerPrincipal' : IDL.Opt(IDL.Principal),
  'timestamp' : IDL.Int,
  'totalGritSpent' : IDL.Nat,
  'minerGritSpent' : IDL.Vec(IDL.Tuple(MinerId, IDL.Nat)),
  'minerCount' : IDL.Nat,
});
export const BlockRecord = IDL.Record({
  'winnerMinerId' : IDL.Opt(MinerId),
  'minerParticipants' : IDL.Vec(IDL.Tuple(MinerId, IDL.Principal)),
  'blockNumber' : IDL.Nat,
  'minerWeights' : IDL.Vec(IDL.Tuple(MinerId, IDL.Float64)),
  'vrfValue' : IDL.Nat64,
  'akkReward' : IDL.Nat,
  'timestamp' : IDL.Int,
  'totalGritSpent' : IDL.Nat,
  'minerGritSpent' : IDL.Vec(IDL.Tuple(MinerId, IDL.Nat)),
  'winnerOwner' : IDL.Opt(IDL.Principal),
});
export const Account = IDL.Record({
  'owner' : IDL.Principal,
  'subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
export const ChainFeeEntry = IDL.Record({
  'feeWei' : IDL.Nat,
  'chain' : IDL.Text,
});
export const MinerStatus = IDL.Variant({
  'active' : IDL.Null,
  'exhausted' : IDL.Null,
  'paused' : IDL.Null,
});
export const MinerView = IDL.Record({
  'id' : MinerId,
  'blocksMined' : IDL.Nat,
  'status' : MinerStatus,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'miningRate' : IDL.Nat,
  'lastProcessedBlock' : IDL.Nat,
  'gritBalance' : IDL.Nat,
  'gritSpent' : IDL.Nat,
});
export const SocialLink = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
export const PublicProfile = IDL.Record({
  'bio' : IDL.Text,
  'hasOgBadge' : IDL.Bool,
  'playerBadgeLevel' : IDL.Nat,
  'username' : IDL.Text,
  'tribeId' : IDL.Opt(IDL.Text),
  'superpowers' : IDL.Text,
  'displayName' : IDL.Text,
  'born' : IDL.Text,
  'socials' : IDL.Vec(SocialLink),
  'coverImage' : IDL.Text,
  'miningStreak' : IDL.Nat,
  'profilePicture' : IDL.Text,
  'evmAddress' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const PlayerScoreEntry = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'tribeId' : IDL.Opt(TribeId),
  'displayName' : IDL.Text,
  'rank' : IDL.Nat,
  'score' : IDL.Float64,
  'tribeName' : IDL.Text,
});
export const TribeScoreEntry = IDL.Record({
  'tribeId' : TribeId,
  'rank' : IDL.Nat,
  'memberCount' : IDL.Nat,
  'score' : IDL.Float64,
  'tribeName' : IDL.Text,
});
export const TribeMemberWithRole = IDL.Record({
  'username' : IDL.Text,
  'userId' : IDL.Text,
  'isLeader' : IDL.Bool,
});
export const ProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'superpowers' : IDL.Text,
  'displayName' : IDL.Text,
  'born' : IDL.Text,
  'socials' : IDL.Vec(SocialLink),
  'coverImage' : IDL.Text,
  'profilePicture' : IDL.Text,
  'evmAddress' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'hasOgBadge' : IDL.Bool,
  'playerBadgeLevel' : IDL.Nat,
  'username' : IDL.Text,
  'superpowers' : IDL.Text,
  'displayName' : IDL.Text,
  'born' : IDL.Text,
  'socials' : IDL.Vec(SocialLink),
  'coverImage' : IDL.Text,
  'miningStreak' : IDL.Nat,
  'profilePicture' : IDL.Text,
  'evmAddress' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const ProfileError = IDL.Variant({
  'bioTooLong' : IDL.Null,
  'usernameTooLong' : IDL.Null,
  'superpowersTooLong' : IDL.Null,
  'usernameRequired' : IDL.Null,
  'locationTooLong' : IDL.Null,
  'socialLinkTooLong' : IDL.Null,
  'displayNameTooLong' : IDL.Null,
  'usernameAlreadyTaken' : IDL.Null,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'addToken' : IDL.Func([AllowlistedToken], [], []),
  'bootstrapAdmin' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'claimOgBadge' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'clearAbandonedMints' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'clearPendingMints' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'clearTestScore' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createMiner' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : MinerId, 'err' : IDL.Text })],
      [],
    ),
  'createTribe' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : Tribe, 'err' : TribeError })],
      [],
    ),
  'creditAbandonedMints' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'editMiner' : IDL.Func(
      [
        MinerId,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Bool),
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'editTribe' : IDL.Func(
      [
        TribeId,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : Tribe, 'err' : TribeError })],
      [],
    ),
  'getAbandonedMints' : IDL.Func([], [IDL.Vec(MintRetryView)], []),
  'getAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAkkBalance' : IDL.Func([], [IDL.Nat], []),
  'getAkkLedgerCanisterId' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getAkkTransferFee' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllClaimHistory' : IDL.Func([], [IDL.Vec(ClaimRecord)], []),
  'getAllowlistAuditLog' : IDL.Func([], [IDL.Vec(AuditLogEntry)], []),
  'getAppPrincipal' : IDL.Func([], [IDL.Principal], ['query']),
  'getBlockDetails' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(BlockDetailView)],
      ['query'],
    ),
  'getBlockHistory' : IDL.Func([IDL.Nat], [IDL.Vec(BlockRecord)], ['query']),
  'getBlockHistoryPage' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(BlockRecord)],
      ['query'],
    ),
  'getCurrentBlockInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'nextBlockIn' : IDL.Nat,
          'blockNumber' : IDL.Nat,
          'lastBlockTime' : IDL.Int,
          'isMiningActive' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getFeePercent' : IDL.Func([], [IDL.Float64], ['query']),
  'getFeeRecipient' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getGritIssuanceRate' : IDL.Func([], [IDL.Nat], ['query']),
  'getHistoryBasedAk69Stockpile' : IDL.Func([], [IDL.Float64], ['query']),
  'getIsLaunched' : IDL.Func([], [IDL.Bool], ['query']),
  'getLaunchGate' : IDL.Func(
      [],
      [
        IDL.Record({
          'startTime' : IDL.Int,
          'endTime' : IDL.Int,
          'enabled' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getLaunchGateConfig' : IDL.Func(
      [],
      [
        IDL.Record({
          'startTime' : IDL.Int,
          'endTime' : IDL.Int,
          'nftGateEnabled' : IDL.Bool,
          'launchTime' : IDL.Int,
          'timeWindowEnabled' : IDL.Bool,
          'launchTimeEnabled' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getLedgerMintingAccount' : IDL.Func([], [IDL.Opt(Account)], []),
  'getMinerCreationFees' : IDL.Func([], [IDL.Vec(ChainFeeEntry)], ['query']),
  'getMintRetryStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalAbandoned' : IDL.Nat,
          'totalRetried' : IDL.Nat,
          'queueDepth' : IDL.Nat,
          'totalSucceeded' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getMyBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyClaimHistory' : IDL.Func([], [IDL.Vec(ClaimRecord)], ['query']),
  'getMyMiners' : IDL.Func([], [IDL.Vec(MinerView)], ['query']),
  'getMyOwnedTribes' : IDL.Func([], [IDL.Vec(Tribe)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(PublicProfile)], ['query']),
  'getMyTribe' : IDL.Func([], [IDL.Opt(Tribe)], ['query']),
  'getPendingMints' : IDL.Func([], [IDL.Vec(MintRetryView)], []),
  'getPlayerBurnSummary' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getPlayerRank' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'getPlayerScore' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Float64],
      ['query'],
    ),
  'getPlayerStreak' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getPrincipalByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'getProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PublicProfile)],
      ['query'],
    ),
  'getProtocolBurnSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalBurnUsd' : IDL.Float64,
          'totalGritFromBurns' : IDL.Nat,
          'byToken' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64, IDL.Float64)),
        }),
      ],
      ['query'],
    ),
  'getProtocolStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalMiners' : IDL.Nat,
          'nextBlockIn' : IDL.Nat,
          'isMiningActive' : IDL.Bool,
          'totalAkkMined' : IDL.Nat,
          'blockReward' : IDL.Nat,
          'totalGritSpent' : IDL.Nat,
          'activeMiners' : IDL.Nat,
          'blocksUntilHalving' : IDL.Nat,
          'currentBlock' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getSupplyVsBalanceAudit' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalAkkMined' : IDL.Nat,
          'discrepancy' : IDL.Int,
          'pendingMints' : IDL.Nat,
          'sumOfAllBalances' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTestScore' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
  'getTokens' : IDL.Func([], [IDL.Vec(AllowlistedToken)], ['query']),
  'getTopPlayers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PlayerScoreEntry)],
      ['query'],
    ),
  'getTopTribes' : IDL.Func([IDL.Text], [IDL.Vec(TribeScoreEntry)], ['query']),
  'getTotalAk69Score' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalAkkFromHistory' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalBlockCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTribe' : IDL.Func([TribeId], [IDL.Opt(Tribe)], ['query']),
  'getTribeAkkFromHistory' : IDL.Func([TribeId], [IDL.Nat], ['query']),
  'getTribeBurnSummary' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getTribeByName' : IDL.Func([IDL.Text], [IDL.Opt(Tribe)], ['query']),
  'getTribeLiveStats' : IDL.Func(
      [TribeId],
      [
        IDL.Opt(
          IDL.Record({
            'memberCount' : IDL.Nat,
            'totalGrit' : IDL.Nat,
            'totalAkk' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getTribeMembers' : IDL.Func([TribeId], [IDL.Vec(IDL.Text)], ['query']),
  'getTribeMembersWithRoles' : IDL.Func(
      [TribeId],
      [IDL.Vec(TribeMemberWithRole)],
      ['query'],
    ),
  'getTribeRank' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'getTribeScore' : IDL.Func([IDL.Text, IDL.Text], [IDL.Float64], ['query']),
  'getUserMiningStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'blocksMined' : IDL.Nat,
          'akkWon' : IDL.Nat,
          'gritSpent' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'hasUsername' : IDL.Func([], [IDL.Bool], ['query']),
  'initiateClaim' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'joinTribe' : IDL.Func(
      [TribeId],
      [IDL.Variant({ 'ok' : Tribe, 'err' : TribeError })],
      [],
    ),
  'leaveTribe' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : TribeError })],
      [],
    ),
  'recalculateTotalAkkMined' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'recheckClaimByHash' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'recheckPendingClaims' : IDL.Func([], [], []),
  'removeAdmin' : IDL.Func([IDL.Principal], [], []),
  'removeToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'resetAkkLedgerCanisterId' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'resetAndClaimAdmin' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'retryFeeClaim' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'retryMint' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
      [],
    ),
  'saveMyProfile' : IDL.Func(
      [ProfileInput],
      [IDL.Variant({ 'ok' : Profile, 'err' : ProfileError })],
      [],
    ),
  'searchTribes' : IDL.Func([IDL.Text], [IDL.Vec(Tribe)], ['query']),
  'setAkkLedgerCanisterId' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setAkkTransferFee' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setFeePercent' : IDL.Func([IDL.Float64], [], []),
  'setFeeRecipient' : IDL.Func([IDL.Text], [], []),
  'setGritIssuanceRate' : IDL.Func([IDL.Nat], [], []),
  'setLaunchGate' : IDL.Func([IDL.Bool, IDL.Int, IDL.Int], [], []),
  'setLaunchTimeGate' : IDL.Func([IDL.Bool, IDL.Int], [], []),
  'setLaunched' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setMinerCreationFee' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setNftGate' : IDL.Func([IDL.Bool], [], []),
  'setTestScore' : IDL.Func(
      [IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'transferTribeOwnership' : IDL.Func(
      [TribeId, IDL.Text],
      [IDL.Variant({ 'ok' : Tribe, 'err' : TribeError })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformPriceResponse' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformResponse' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePlayerBadge' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'whoami' : IDL.Func([], [IDL.Principal], ['query']),
  'withdrawAkk' : IDL.Func(
      [Account, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AllowlistedToken = IDL.Record({
    'decimals' : IDL.Nat,
    'tokenAddress' : IDL.Text,
    'chain' : IDL.Text,
    'name' : IDL.Text,
    'priceUSD' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const MinerId = IDL.Nat;
  const TribeId = IDL.Text;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Tribe = IDL.Record({
    'id' : TribeId,
    'coverImageUrl' : IDL.Opt(IDL.Text),
    'ownerId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'memberCount' : IDL.Nat,
    'description' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'cumulativeAkk' : IDL.Nat,
    'cumulativeGrit' : IDL.Nat,
  });
  const TribeError = IDL.Variant({
    'nameTaken' : IDL.Null,
    'noUsername' : IDL.Null,
    'newOwnerMaxTribes' : IDL.Null,
    'descriptionTooLong' : IDL.Null,
    'notMember' : IDL.Null,
    'newOwnerNotFound' : IDL.Null,
    'alreadyMember' : IDL.Null,
    'notFound' : IDL.Null,
    'nameTooLong' : IDL.Null,
    'notOwner' : IDL.Null,
    'maxTribesReached' : IDL.Null,
    'newOwnerNoUsername' : IDL.Null,
  });
  const MintRetryView = IDL.Record({
    'owner' : IDL.Principal,
    'lastAttemptTime' : IDL.Int,
    'blockId' : IDL.Nat,
    'minerId' : IDL.Text,
    'attempts' : IDL.Nat,
    'error' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const ClaimStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'pendingFee' : IDL.Null,
    'failed' : IDL.Null,
  });
  const ClaimRecord = IDL.Record({
    'status' : ClaimStatus,
    'amountBurned' : IDL.Float64,
    'gritMinted' : IDL.Nat,
    'claimant' : IDL.Principal,
    'tokenAddress' : IDL.Text,
    'chain' : IDL.Text,
    'tokenDecimals' : IDL.Nat,
    'tokenSymbol' : IDL.Text,
    'usdValue' : IDL.Float64,
    'timestamp' : IDL.Int,
    'txHash' : IDL.Text,
    'feeTxHash' : IDL.Opt(IDL.Text),
  });
  const AuditAction = IDL.Variant({ 'add' : IDL.Null, 'remove' : IDL.Null });
  const AuditLogEntry = IDL.Record({
    'action' : AuditAction,
    'adminPrincipal' : IDL.Principal,
    'tokenAddress' : IDL.Text,
    'chain' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const BlockDetailView = IDL.Record({
    'winnerMinerId' : IDL.Opt(MinerId),
    'minerParticipants' : IDL.Vec(IDL.Tuple(MinerId, IDL.Principal)),
    'blockNumber' : IDL.Nat,
    'minerWeights' : IDL.Vec(IDL.Tuple(MinerId, IDL.Float64)),
    'vrfValue' : IDL.Nat64,
    'akkReward' : IDL.Nat,
    'winnerPrincipal' : IDL.Opt(IDL.Principal),
    'timestamp' : IDL.Int,
    'totalGritSpent' : IDL.Nat,
    'minerGritSpent' : IDL.Vec(IDL.Tuple(MinerId, IDL.Nat)),
    'minerCount' : IDL.Nat,
  });
  const BlockRecord = IDL.Record({
    'winnerMinerId' : IDL.Opt(MinerId),
    'minerParticipants' : IDL.Vec(IDL.Tuple(MinerId, IDL.Principal)),
    'blockNumber' : IDL.Nat,
    'minerWeights' : IDL.Vec(IDL.Tuple(MinerId, IDL.Float64)),
    'vrfValue' : IDL.Nat64,
    'akkReward' : IDL.Nat,
    'timestamp' : IDL.Int,
    'totalGritSpent' : IDL.Nat,
    'minerGritSpent' : IDL.Vec(IDL.Tuple(MinerId, IDL.Nat)),
    'winnerOwner' : IDL.Opt(IDL.Principal),
  });
  const Account = IDL.Record({
    'owner' : IDL.Principal,
    'subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const ChainFeeEntry = IDL.Record({ 'feeWei' : IDL.Nat, 'chain' : IDL.Text });
  const MinerStatus = IDL.Variant({
    'active' : IDL.Null,
    'exhausted' : IDL.Null,
    'paused' : IDL.Null,
  });
  const MinerView = IDL.Record({
    'id' : MinerId,
    'blocksMined' : IDL.Nat,
    'status' : MinerStatus,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'miningRate' : IDL.Nat,
    'lastProcessedBlock' : IDL.Nat,
    'gritBalance' : IDL.Nat,
    'gritSpent' : IDL.Nat,
  });
  const SocialLink = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
  const PublicProfile = IDL.Record({
    'bio' : IDL.Text,
    'hasOgBadge' : IDL.Bool,
    'playerBadgeLevel' : IDL.Nat,
    'username' : IDL.Text,
    'tribeId' : IDL.Opt(IDL.Text),
    'superpowers' : IDL.Text,
    'displayName' : IDL.Text,
    'born' : IDL.Text,
    'socials' : IDL.Vec(SocialLink),
    'coverImage' : IDL.Text,
    'miningStreak' : IDL.Nat,
    'profilePicture' : IDL.Text,
    'evmAddress' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const PlayerScoreEntry = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'tribeId' : IDL.Opt(TribeId),
    'displayName' : IDL.Text,
    'rank' : IDL.Nat,
    'score' : IDL.Float64,
    'tribeName' : IDL.Text,
  });
  const TribeScoreEntry = IDL.Record({
    'tribeId' : TribeId,
    'rank' : IDL.Nat,
    'memberCount' : IDL.Nat,
    'score' : IDL.Float64,
    'tribeName' : IDL.Text,
  });
  const TribeMemberWithRole = IDL.Record({
    'username' : IDL.Text,
    'userId' : IDL.Text,
    'isLeader' : IDL.Bool,
  });
  const ProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'superpowers' : IDL.Text,
    'displayName' : IDL.Text,
    'born' : IDL.Text,
    'socials' : IDL.Vec(SocialLink),
    'coverImage' : IDL.Text,
    'profilePicture' : IDL.Text,
    'evmAddress' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'hasOgBadge' : IDL.Bool,
    'playerBadgeLevel' : IDL.Nat,
    'username' : IDL.Text,
    'superpowers' : IDL.Text,
    'displayName' : IDL.Text,
    'born' : IDL.Text,
    'socials' : IDL.Vec(SocialLink),
    'coverImage' : IDL.Text,
    'miningStreak' : IDL.Nat,
    'profilePicture' : IDL.Text,
    'evmAddress' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const ProfileError = IDL.Variant({
    'bioTooLong' : IDL.Null,
    'usernameTooLong' : IDL.Null,
    'superpowersTooLong' : IDL.Null,
    'usernameRequired' : IDL.Null,
    'locationTooLong' : IDL.Null,
    'socialLinkTooLong' : IDL.Null,
    'displayNameTooLong' : IDL.Null,
    'usernameAlreadyTaken' : IDL.Null,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'addToken' : IDL.Func([AllowlistedToken], [], []),
    'bootstrapAdmin' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'claimOgBadge' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'clearAbandonedMints' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'clearPendingMints' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'clearTestScore' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createMiner' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : MinerId, 'err' : IDL.Text })],
        [],
      ),
    'createTribe' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : Tribe, 'err' : TribeError })],
        [],
      ),
    'creditAbandonedMints' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'editMiner' : IDL.Func(
        [
          MinerId,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Bool),
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'editTribe' : IDL.Func(
        [
          TribeId,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : Tribe, 'err' : TribeError })],
        [],
      ),
    'getAbandonedMints' : IDL.Func([], [IDL.Vec(MintRetryView)], []),
    'getAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAkkBalance' : IDL.Func([], [IDL.Nat], []),
    'getAkkLedgerCanisterId' : IDL.Func(
        [],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getAkkTransferFee' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllClaimHistory' : IDL.Func([], [IDL.Vec(ClaimRecord)], []),
    'getAllowlistAuditLog' : IDL.Func([], [IDL.Vec(AuditLogEntry)], []),
    'getAppPrincipal' : IDL.Func([], [IDL.Principal], ['query']),
    'getBlockDetails' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(BlockDetailView)],
        ['query'],
      ),
    'getBlockHistory' : IDL.Func([IDL.Nat], [IDL.Vec(BlockRecord)], ['query']),
    'getBlockHistoryPage' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(BlockRecord)],
        ['query'],
      ),
    'getCurrentBlockInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'nextBlockIn' : IDL.Nat,
            'blockNumber' : IDL.Nat,
            'lastBlockTime' : IDL.Int,
            'isMiningActive' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getFeePercent' : IDL.Func([], [IDL.Float64], ['query']),
    'getFeeRecipient' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getGritIssuanceRate' : IDL.Func([], [IDL.Nat], ['query']),
    'getHistoryBasedAk69Stockpile' : IDL.Func([], [IDL.Float64], ['query']),
    'getIsLaunched' : IDL.Func([], [IDL.Bool], ['query']),
    'getLaunchGate' : IDL.Func(
        [],
        [
          IDL.Record({
            'startTime' : IDL.Int,
            'endTime' : IDL.Int,
            'enabled' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getLaunchGateConfig' : IDL.Func(
        [],
        [
          IDL.Record({
            'startTime' : IDL.Int,
            'endTime' : IDL.Int,
            'nftGateEnabled' : IDL.Bool,
            'launchTime' : IDL.Int,
            'timeWindowEnabled' : IDL.Bool,
            'launchTimeEnabled' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getLedgerMintingAccount' : IDL.Func([], [IDL.Opt(Account)], []),
    'getMinerCreationFees' : IDL.Func([], [IDL.Vec(ChainFeeEntry)], ['query']),
    'getMintRetryStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalAbandoned' : IDL.Nat,
            'totalRetried' : IDL.Nat,
            'queueDepth' : IDL.Nat,
            'totalSucceeded' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getMyBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyClaimHistory' : IDL.Func([], [IDL.Vec(ClaimRecord)], ['query']),
    'getMyMiners' : IDL.Func([], [IDL.Vec(MinerView)], ['query']),
    'getMyOwnedTribes' : IDL.Func([], [IDL.Vec(Tribe)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(PublicProfile)], ['query']),
    'getMyTribe' : IDL.Func([], [IDL.Opt(Tribe)], ['query']),
    'getPendingMints' : IDL.Func([], [IDL.Vec(MintRetryView)], []),
    'getPlayerBurnSummary' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getPlayerRank' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getPlayerScore' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Float64],
        ['query'],
      ),
    'getPlayerStreak' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getPrincipalByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PublicProfile)],
        ['query'],
      ),
    'getProtocolBurnSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalBurnUsd' : IDL.Float64,
            'totalGritFromBurns' : IDL.Nat,
            'byToken' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64, IDL.Float64)),
          }),
        ],
        ['query'],
      ),
    'getProtocolStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalMiners' : IDL.Nat,
            'nextBlockIn' : IDL.Nat,
            'isMiningActive' : IDL.Bool,
            'totalAkkMined' : IDL.Nat,
            'blockReward' : IDL.Nat,
            'totalGritSpent' : IDL.Nat,
            'activeMiners' : IDL.Nat,
            'blocksUntilHalving' : IDL.Nat,
            'currentBlock' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getSupplyVsBalanceAudit' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalAkkMined' : IDL.Nat,
            'discrepancy' : IDL.Int,
            'pendingMints' : IDL.Nat,
            'sumOfAllBalances' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTestScore' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
    'getTokens' : IDL.Func([], [IDL.Vec(AllowlistedToken)], ['query']),
    'getTopPlayers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PlayerScoreEntry)],
        ['query'],
      ),
    'getTopTribes' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TribeScoreEntry)],
        ['query'],
      ),
    'getTotalAk69Score' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalAkkFromHistory' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalBlockCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTribe' : IDL.Func([TribeId], [IDL.Opt(Tribe)], ['query']),
    'getTribeAkkFromHistory' : IDL.Func([TribeId], [IDL.Nat], ['query']),
    'getTribeBurnSummary' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getTribeByName' : IDL.Func([IDL.Text], [IDL.Opt(Tribe)], ['query']),
    'getTribeLiveStats' : IDL.Func(
        [TribeId],
        [
          IDL.Opt(
            IDL.Record({
              'memberCount' : IDL.Nat,
              'totalGrit' : IDL.Nat,
              'totalAkk' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getTribeMembers' : IDL.Func([TribeId], [IDL.Vec(IDL.Text)], ['query']),
    'getTribeMembersWithRoles' : IDL.Func(
        [TribeId],
        [IDL.Vec(TribeMemberWithRole)],
        ['query'],
      ),
    'getTribeRank' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getTribeScore' : IDL.Func([IDL.Text, IDL.Text], [IDL.Float64], ['query']),
    'getUserMiningStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'blocksMined' : IDL.Nat,
            'akkWon' : IDL.Nat,
            'gritSpent' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'hasUsername' : IDL.Func([], [IDL.Bool], ['query']),
    'initiateClaim' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'joinTribe' : IDL.Func(
        [TribeId],
        [IDL.Variant({ 'ok' : Tribe, 'err' : TribeError })],
        [],
      ),
    'leaveTribe' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : TribeError })],
        [],
      ),
    'recalculateTotalAkkMined' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'recheckClaimByHash' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'recheckPendingClaims' : IDL.Func([], [], []),
    'removeAdmin' : IDL.Func([IDL.Principal], [], []),
    'removeToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'resetAkkLedgerCanisterId' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'resetAndClaimAdmin' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'retryFeeClaim' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'retryMint' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'saveMyProfile' : IDL.Func(
        [ProfileInput],
        [IDL.Variant({ 'ok' : Profile, 'err' : ProfileError })],
        [],
      ),
    'searchTribes' : IDL.Func([IDL.Text], [IDL.Vec(Tribe)], ['query']),
    'setAkkLedgerCanisterId' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setAkkTransferFee' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setFeePercent' : IDL.Func([IDL.Float64], [], []),
    'setFeeRecipient' : IDL.Func([IDL.Text], [], []),
    'setGritIssuanceRate' : IDL.Func([IDL.Nat], [], []),
    'setLaunchGate' : IDL.Func([IDL.Bool, IDL.Int, IDL.Int], [], []),
    'setLaunchTimeGate' : IDL.Func([IDL.Bool, IDL.Int], [], []),
    'setLaunched' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setMinerCreationFee' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setNftGate' : IDL.Func([IDL.Bool], [], []),
    'setTestScore' : IDL.Func(
        [IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'transferTribeOwnership' : IDL.Func(
        [TribeId, IDL.Text],
        [IDL.Variant({ 'ok' : Tribe, 'err' : TribeError })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformPriceResponse' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformResponse' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePlayerBadge' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'whoami' : IDL.Func([], [IDL.Principal], ['query']),
    'withdrawAkk' : IDL.Func(
        [Account, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };