/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'owner' : Principal,
  'subaccount' : [] | [Uint8Array],
}
export interface AllowlistedToken {
  'decimals' : bigint,
  'tokenAddress' : string,
  'chain' : string,
  'name' : string,
  'priceUSD' : number,
  'symbol' : string,
}
export type AuditAction = { 'add' : null } |
  { 'remove' : null };
export interface AuditLogEntry {
  'action' : AuditAction,
  'adminPrincipal' : Principal,
  'tokenAddress' : string,
  'chain' : string,
  'timestamp' : bigint,
}
export interface BlockDetailView {
  'winnerMinerId' : [] | [MinerId],
  'minerParticipants' : Array<[MinerId, Principal]>,
  'blockNumber' : bigint,
  'minerWeights' : Array<[MinerId, number]>,
  'vrfValue' : bigint,
  'akkReward' : bigint,
  'winnerPrincipal' : [] | [Principal],
  'timestamp' : bigint,
  'totalGritSpent' : bigint,
  'minerGritSpent' : Array<[MinerId, bigint]>,
  'minerCount' : bigint,
}
export interface BlockRecord {
  'winnerMinerId' : [] | [MinerId],
  'minerParticipants' : Array<[MinerId, Principal]>,
  'blockNumber' : bigint,
  'minerWeights' : Array<[MinerId, number]>,
  'vrfValue' : bigint,
  'akkReward' : bigint,
  'timestamp' : bigint,
  'totalGritSpent' : bigint,
  'minerGritSpent' : Array<[MinerId, bigint]>,
  'winnerOwner' : [] | [Principal],
}
export interface Cell { 'value' : Value, 'name' : string }
export interface ChainFeeEntry { 'feeWei' : bigint, 'chain' : string }
export interface ClaimRecord {
  'status' : ClaimStatus,
  'amountBurned' : number,
  'gritMinted' : bigint,
  'claimant' : Principal,
  'tokenAddress' : string,
  'chain' : string,
  'tokenDecimals' : bigint,
  'tokenSymbol' : string,
  'usdValue' : number,
  'timestamp' : bigint,
  'txHash' : string,
  'feeTxHash' : [] | [string],
}
export type ClaimStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'pendingFee' : null } |
  { 'failed' : null };
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type MinerId = bigint;
export type MinerStatus = { 'active' : null } |
  { 'exhausted' : null } |
  { 'paused' : null };
export interface MinerView {
  'id' : MinerId,
  'blocksMined' : bigint,
  'status' : MinerStatus,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'miningRate' : bigint,
  'lastProcessedBlock' : bigint,
  'gritBalance' : bigint,
  'gritSpent' : bigint,
}
export interface MintRetryView {
  'owner' : Principal,
  'lastAttemptTime' : bigint,
  'blockId' : bigint,
  'minerId' : string,
  'attempts' : bigint,
  'error' : string,
  'amount' : bigint,
}
export interface PlayerScoreEntry {
  'principal' : Principal,
  'username' : string,
  'tribeId' : [] | [TribeId],
  'displayName' : string,
  'rank' : bigint,
  'score' : number,
  'tribeName' : string,
}
export interface Profile {
  'bio' : string,
  'hasOgBadge' : boolean,
  'playerBadgeLevel' : bigint,
  'username' : string,
  'superpowers' : string,
  'displayName' : string,
  'born' : string,
  'socials' : Array<SocialLink>,
  'coverImage' : string,
  'miningStreak' : bigint,
  'profilePicture' : string,
  'evmAddress' : [] | [string],
  'location' : string,
}
export type ProfileError = { 'bioTooLong' : null } |
  { 'usernameTooLong' : null } |
  { 'superpowersTooLong' : null } |
  { 'usernameRequired' : null } |
  { 'locationTooLong' : null } |
  { 'socialLinkTooLong' : null } |
  { 'displayNameTooLong' : null } |
  { 'usernameAlreadyTaken' : null };
export interface ProfileInput {
  'bio' : string,
  'username' : string,
  'superpowers' : string,
  'displayName' : string,
  'born' : string,
  'socials' : Array<SocialLink>,
  'coverImage' : string,
  'profilePicture' : string,
  'evmAddress' : [] | [string],
  'location' : string,
}
export interface PublicProfile {
  'bio' : string,
  'hasOgBadge' : boolean,
  'playerBadgeLevel' : bigint,
  'username' : string,
  'tribeId' : [] | [string],
  'superpowers' : string,
  'displayName' : string,
  'born' : string,
  'socials' : Array<SocialLink>,
  'coverImage' : string,
  'miningStreak' : bigint,
  'profilePicture' : string,
  'evmAddress' : [] | [string],
  'location' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface SocialLink { 'url' : string, 'name' : string }
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface Tribe {
  'id' : TribeId,
  'coverImageUrl' : [] | [string],
  'ownerId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'memberCount' : bigint,
  'description' : string,
  'photoUrl' : [] | [string],
  'cumulativeAkk' : bigint,
  'cumulativeGrit' : bigint,
}
export type TribeError = { 'nameTaken' : null } |
  { 'noUsername' : null } |
  { 'newOwnerMaxTribes' : null } |
  { 'descriptionTooLong' : null } |
  { 'notMember' : null } |
  { 'newOwnerNotFound' : null } |
  { 'alreadyMember' : null } |
  { 'notFound' : null } |
  { 'nameTooLong' : null } |
  { 'notOwner' : null } |
  { 'maxTribesReached' : null } |
  { 'newOwnerNoUsername' : null };
export type TribeId = string;
export interface TribeMemberWithRole {
  'username' : string,
  'userId' : string,
  'isLeader' : boolean,
}
export interface TribeScoreEntry {
  'tribeId' : TribeId,
  'rank' : bigint,
  'memberCount' : bigint,
  'score' : number,
  'tribeName' : string,
}
export type UserId = Principal;
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'addToken' : ActorMethod<[AllowlistedToken], undefined>,
  'bootstrapAdmin' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'claimOgBadge' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'clearAbandonedMints' : ActorMethod<
    [],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'clearPendingMints' : ActorMethod<[], { 'ok' : bigint } | { 'err' : string }>,
  'clearTestScore' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'createMiner' : ActorMethod<
    [string, bigint, bigint],
    { 'ok' : MinerId } |
      { 'err' : string }
  >,
  'createTribe' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    { 'ok' : Tribe } |
      { 'err' : TribeError }
  >,
  'creditAbandonedMints' : ActorMethod<
    [],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'editMiner' : ActorMethod<
    [MinerId, [] | [string], [] | [bigint], [] | [bigint], [] | [boolean]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'editTribe' : ActorMethod<
    [TribeId, [] | [string], [] | [string], [] | [string], [] | [string]],
    { 'ok' : Tribe } |
      { 'err' : TribeError }
  >,
  'execute' : ActorMethod<[string], Result>,
  'getAbandonedMints' : ActorMethod<[], Array<MintRetryView>>,
  'getAdmins' : ActorMethod<[], Array<Principal>>,
  'getAkkBalance' : ActorMethod<[], bigint>,
  'getAkkLedgerCanisterId' : ActorMethod<[], [] | [Principal]>,
  'getAkkTransferFee' : ActorMethod<[], bigint>,
  'getAllClaimHistory' : ActorMethod<[], Array<ClaimRecord>>,
  'getAllowlistAuditLog' : ActorMethod<[], Array<AuditLogEntry>>,
  'getAppPrincipal' : ActorMethod<[], Principal>,
  'getBlockDetails' : ActorMethod<[bigint], [] | [BlockDetailView]>,
  'getBlockHistory' : ActorMethod<[bigint], Array<BlockRecord>>,
  'getBlockHistoryPage' : ActorMethod<[bigint, bigint], Array<BlockRecord>>,
  'getCurrentBlockInfo' : ActorMethod<
    [],
    {
      'nextBlockIn' : bigint,
      'blockNumber' : bigint,
      'lastBlockTime' : bigint,
      'isMiningActive' : boolean,
    }
  >,
  'getFeePercent' : ActorMethod<[], number>,
  'getFeeRecipient' : ActorMethod<[], [] | [string]>,
  'getGritIssuanceRate' : ActorMethod<[], bigint>,
  'getHistoryBasedAk69Stockpile' : ActorMethod<[], number>,
  'getIsLaunched' : ActorMethod<[], boolean>,
  'getLaunchGate' : ActorMethod<
    [],
    { 'startTime' : bigint, 'endTime' : bigint, 'enabled' : boolean }
  >,
  'getLaunchGateConfig' : ActorMethod<
    [],
    {
      'startTime' : bigint,
      'endTime' : bigint,
      'nftGateEnabled' : boolean,
      'launchTime' : bigint,
      'timeWindowEnabled' : boolean,
      'launchTimeEnabled' : boolean,
    }
  >,
  'getLedgerMintingAccount' : ActorMethod<[], [] | [Account]>,
  'getMinerCreationFees' : ActorMethod<[], Array<ChainFeeEntry>>,
  'getMintRetryStats' : ActorMethod<
    [],
    {
      'totalAbandoned' : bigint,
      'totalRetried' : bigint,
      'queueDepth' : bigint,
      'totalSucceeded' : bigint,
    }
  >,
  'getMyBalance' : ActorMethod<[], bigint>,
  'getMyClaimHistory' : ActorMethod<[], Array<ClaimRecord>>,
  'getMyMiners' : ActorMethod<[], Array<MinerView>>,
  'getMyOwnedTribes' : ActorMethod<[], Array<Tribe>>,
  'getMyProfile' : ActorMethod<[], [] | [PublicProfile]>,
  'getMyTribe' : ActorMethod<[], [] | [Tribe]>,
  'getPendingMints' : ActorMethod<[], Array<MintRetryView>>,
  'getPlayerBurnSummary' : ActorMethod<[Principal], Array<[string, number]>>,
  'getPlayerRank' : ActorMethod<[Principal, string], [] | [bigint]>,
  'getPlayerScore' : ActorMethod<[Principal, string], number>,
  'getPlayerStreak' : ActorMethod<[Principal], bigint>,
  'getPrincipalByUsername' : ActorMethod<[string], [] | [Principal]>,
  'getProfileByUsername' : ActorMethod<[string], [] | [PublicProfile]>,
  'getProtocolBurnSummary' : ActorMethod<
    [],
    {
      'totalBurnUsd' : number,
      'totalGritFromBurns' : bigint,
      'byToken' : Array<[string, number, number]>,
    }
  >,
  'getProtocolStats' : ActorMethod<
    [],
    {
      'totalMiners' : bigint,
      'nextBlockIn' : bigint,
      'isMiningActive' : boolean,
      'totalAkkMined' : bigint,
      'blockReward' : bigint,
      'totalGritSpent' : bigint,
      'activeMiners' : bigint,
      'blocksUntilHalving' : bigint,
      'currentBlock' : bigint,
    }
  >,
  'getTestScore' : ActorMethod<[], [] | [number]>,
  'getTokens' : ActorMethod<[], Array<AllowlistedToken>>,
  'getTopPlayers' : ActorMethod<[string], Array<PlayerScoreEntry>>,
  'getTopTribes' : ActorMethod<[string], Array<TribeScoreEntry>>,
  'getTotalAk69Score' : ActorMethod<[], number>,
  'getTotalAkkFromHistory' : ActorMethod<[], bigint>,
  'getTotalBlockCount' : ActorMethod<[], bigint>,
  'getTribe' : ActorMethod<[TribeId], [] | [Tribe]>,
  'getTribeAkkFromHistory' : ActorMethod<[TribeId], bigint>,
  'getTribeBurnSummary' : ActorMethod<[string], Array<[string, number]>>,
  'getTribeByName' : ActorMethod<[string], [] | [Tribe]>,
  'getTribeLiveStats' : ActorMethod<
    [TribeId],
    [] | [{ 'memberCount' : bigint, 'totalGrit' : bigint, 'totalAkk' : bigint }]
  >,
  'getTribeMembers' : ActorMethod<[TribeId], Array<string>>,
  'getTribeMembersWithRoles' : ActorMethod<
    [TribeId],
    Array<TribeMemberWithRole>
  >,
  'getTribeRank' : ActorMethod<[string, string], [] | [bigint]>,
  'getTribeScore' : ActorMethod<[string, string], number>,
  'getUserMiningStats' : ActorMethod<
    [],
    { 'blocksMined' : bigint, 'akkWon' : bigint, 'gritSpent' : bigint }
  >,
  'hasUsername' : ActorMethod<[], boolean>,
  'initiateClaim' : ActorMethod<
    [string, string, string, string, number],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'isUsernameAvailable' : ActorMethod<[string], boolean>,
  'joinTribe' : ActorMethod<
    [TribeId],
    { 'ok' : Tribe } |
      { 'err' : TribeError }
  >,
  'leaveTribe' : ActorMethod<[], { 'ok' : null } | { 'err' : TribeError }>,
  'recheckClaimByHash' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'recheckPendingClaims' : ActorMethod<[], undefined>,
  'removeAdmin' : ActorMethod<[Principal], undefined>,
  'removeToken' : ActorMethod<[string, string], undefined>,
  'resetAkkLedgerCanisterId' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'resetAndClaimAdmin' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'retryFeeClaim' : ActorMethod<
    [string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'retryMint' : ActorMethod<[bigint], { 'Ok' : null } | { 'Err' : string }>,
  'saveMyProfile' : ActorMethod<
    [ProfileInput],
    { 'ok' : Profile } |
      { 'err' : ProfileError }
  >,
  'schema' : ActorMethod<[], string>,
  'searchTribes' : ActorMethod<[string], Array<Tribe>>,
  'setAkkLedgerCanisterId' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setAkkTransferFee' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setFeePercent' : ActorMethod<[number], undefined>,
  'setFeeRecipient' : ActorMethod<[string], undefined>,
  'setGritIssuanceRate' : ActorMethod<[bigint], undefined>,
  'setLaunchGate' : ActorMethod<[boolean, bigint, bigint], undefined>,
  'setLaunchTimeGate' : ActorMethod<[boolean, bigint], undefined>,
  'setLaunched' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'setMinerCreationFee' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setNftGate' : ActorMethod<[boolean], undefined>,
  'setTestScore' : ActorMethod<[number], { 'ok' : null } | { 'err' : string }>,
  'transferTribeOwnership' : ActorMethod<
    [TribeId, string],
    { 'ok' : Tribe } |
      { 'err' : TribeError }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'transformPriceResponse' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transformResponse' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'updatePlayerBadge' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'whoami' : ActorMethod<[], Principal>,
  'withdrawAkk' : ActorMethod<
    [Account, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];